### ISSUE TITLE
error from web.dev

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#1547]
```
i18n registration incorrect in: [object Object] TypeError: Cannot read properties of undefined (reading 'includes') at https://hax.psu.edu/cdn/1.x.x/build/es6/node_modules/@lrnwebcomponents/i18n-manager/i18n-manager.js:5:3181 at Array.filter (<anonymous>) at HTMLElement.updateLanguage (https://hax.psu.edu/cdn/1.x.x/build/es6/node_modules/@lrnwebcomponents/i18n-manager/i18n-manager.js:5:3148) at HTMLElement.attributeChangedCallback (https://hax.psu.edu/cdn/1.x.x/build/es6/node_modules/@lrnwebcomponents/i18n-manager/i18n-manager.js:5:4326) at set lang [as lang] (https://hax.psu.edu/cdn/1.x.x/build/es6/node_modules/@lrnwebcomponents/i18n-manager/i18n-manager.js:5:4407) at HTMLElement.changeLanguageEvent (https://hax.psu.edu/cdn/1.x.x/build/es6/node_modules/@lrnwebcomponents/i18n-manager/i18n-manager.js:5:1403) at Store.loadManifest (https://hax.psu.edu/cdn/1.x.x/build/es6/node_modules/@lrnwebcomponents/haxcms-elements/lib/core/haxcms-site-store.js:1:4532)
```

Not sure what that's about but maybe their browser agent doesn't actually have "language" . Probably a simple sanity check on an object

**Comment by btopro** [comment]
no longer there eI believe
