### ISSUE TITLE
Something with RSS format generator and tags not being an array

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#1757]
Something with RSS format generator and tags not being an array. this is in 7.0.16 as deployed on reclaim. Appears to be a PHP level issue w/ some data layer from front end
```
<pre>Array
(
    [type] => 1
    [message] => Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /var/www/webroot/ROOT/system/backend/php/lib/RSS.php:69
Stack trace:
#0 /var/www/webroot/ROOT/system/backend/php/lib/RSS.php(69): implode(',', 'hax,cms,drupal,...')
#1 /var/www/webroot/ROOT/system/backend/php/lib/RSS.php(40): FeedMe->rssItems(Object(HAXCMSSite))
#2 /var/www/webroot/ROOT/system/backend/php/lib/HAXCMSSite.php(695): FeedMe->getRSSFeed(Object(HAXCMSSite))
#3 /var/www/webroot/ROOT/system/backend/php/lib/HAXCMSSite.php(1382): HAXCMSSite->updateAlternateFormats()
#4 /var/www/webroot/ROOT/system/backend/php/lib/Operations.php(730): HAXCMSSite->updateNode(Object(JSONOutlineSchemaItem))
#5 /var/www/webroot/ROOT/system/backend/php/lib/Request.php(101): Operations->saveOutline()
#6 /var/www/webroot/ROOT/system/backend/php/lib/HAXCMS.php(424): Request->execute('saveOutline', Array, Array)
#7 /var/www/webroot/ROOT/system/api.php(5): HAXCMS->executeRequest()
#8 {main}
  thrown
    [file] => /var/www/webroot/ROOT/system/backend/php/lib/RSS.php
    [line] => 69
)
</pre>
```

**Comment by btopro** [comment]
```
Array
(
    [type] => 1
    [message] => Uncaught Error: Call to undefined method SplFixedArray::key() in /var/www/webroot/ROOT/system/backend/php/vendor/icamys/php-sitemap-generator/src/SitemapGenerator.php:233
Stack trace:
#0 /var/www/webroot/ROOT/system/backend/php/lib/HAXCMSSite.php(734): Icamys\SitemapGenerator\SitemapGenerator->addUrl('/item-451a9b3f-...', Object(DateTime), 'daily', '1.0')
#1 /var/www/webroot/ROOT/system/backend/php/lib/HAXCMSSite.php(1382): HAXCMSSite->updateAlternateFormats()
#2 /var/www/webroot/ROOT/system/backend/php/lib/Operations.php(1184): HAXCMSSite->updateNode(Object(JSONOutlineSchemaItem))
#3 /var/www/webroot/ROOT/system/backend/php/lib/Request.php(101): Operations->saveNode()
#4 /var/www/webroot/ROOT/system/backend/php/lib/HAXCMS.php(424): Request->execute('saveNode', Array, Array)
#5 /var/www/webroot/ROOT/system/api.php(5): HAXCMS->executeRequest()
#6 {main}
  thrown
    [file] => /var/www/webroot/ROOT/system/backend/php/vendor/icamys/php-sitemap-generator/src/SitemapGenerator.php
    [line] => 233
)
```

**Comment by btopro** [comment]
1st taken care of; 2nd accounted for at least in squashing error output. my guess is a bad timestamp / made up one on backend in a demo space as I cant replicate.
