### ISSUE TITLE
eerror when invoking multiplee cameras to snap a photo of me for a collection of items

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#1817]
Uncaught (in promise) TypeError: Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.
    at SimpleLoginCamera.renderImage (simple-login-camera.js:1:3451)
    at simple-camera-snap.js:1:3915
    at async SimpleCameraSnap.snapPhoto (simple-camera-snap.js:1:3884)

**Comment by btopro** [comment]
must be too much me for it to handle :small_airplane:
