### ISSUE TITLE
[elmsln] minor regressions notices from most recent update

### ISSUE THREAD

**Issue by btopro** [elmsln/issues#286]
- [x] line-height influences the video-player / tags within for some reason. May need to define these so other systems can't influence it (hax not picking this up)
- [x] video player doesn't always detect youtube correctly. Sometimes it says non mp4 paths === youtube.
- [x] tags wrapped in a paragraph (which is common) need to be able to activate more easily. Sometimes clicking a video-player manually added to a p tag will not activate the video player (as example). (hax-body)

Will activate, need to clean up this error (duplicate generates it)
```
hax-body.js:1276 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at HTMLElement.haxDuplicateNode (http://127.0.0.1:8081/node_modules/@lrnwebcomponents/hax-body/hax-body.js:1276:14)
    at HTMLElement._haxContextOperation (http://127.0.0.1:8081/node_modules/@lrnwebcomponents/hax-body/hax-body.js:1793:16)
    at HTMLElement._fireEvent (http://127.0.0.1:8081/node_modules/@lrnwebcomponents/hax-body/lib/hax-context-item.js:242:12)
    at EventPart.handleEvent (http://127.0.0.1:8081/node_modules/lit-element/node_modules/lit-html/lib/parts.js:507:18)
    at HTMLElement.EventPart.__boundHandleEvent (http://127.0.0.1:8081/node_modules/lit-element/node_modules/lit-html/lib/parts.js:469:41)
```

**Comment by btopro** [comment]
@nikkimk when you get a chacne can you look at the line-height and youtube identification issues mentioned here. These were regressions a few releases ago that were noticed and both I think are easy fixes but video is your land :0)
